import {
  AuditLog,
  Doctor,
  DoctorConnection,
  DoctorSubscription,
  MedicalOffice,
  Patient,
  PaymentTransaction,
  SharedPatient,
  SubscriptionPlan,
  User,
  Visit,
} from "@/types/medical";

// ================= OFFICES =================
export const MOCK_OFFICES: MedicalOffice[] = [
  {
    id: "off_1",
    name: "مطب تخصصی ونک (مهرگان)",
    address: "تهران، میدان ونک، خیابان ولیعصر، برج پزشکان نگین، طبقه ۴",
    phone: "021-88776655",
    city: "تهران",
    doctorCount: 2,
    patientCount: 4,
    createdAt: "2026-01-10T08:00:00.000Z",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "off_2",
    name: "درمانگاه شبانه‌روزی سلامت (سعادت‌آباد)",
    address: "تهران، سعادت‌آباد، میدان کاج، بلوار سرو غربی، پلاک ۲۴",
    phone: "021-22334455",
    city: "تهران",
    doctorCount: 3,
    patientCount: 2,
    createdAt: "2026-02-15T09:00:00.000Z",
    updatedAt: "2026-09-15T12:00:00.000Z",
  },
  {
    id: "off_3",
    name: "مرکز قلب و عروق امید (تهران‌پارس)",
    address: "تهران، فلکه دوم تهرانپارس، خیابان فرجام، ساختمان پزشکان امید",
    phone: "021-77889900",
    city: "تهران",
    doctorCount: 1,
    patientCount: 1,
    createdAt: "2026-03-20T10:00:00.000Z",
    updatedAt: "2026-08-20T14:00:00.000Z",
  },
];

// ================= USERS & RBAC =================
export const MOCK_USERS: User[] = [
  {
    id: "user_doc_1",
    email: "dr.alavi@medidoc.ir",
    fullName: "دکتر سارا علوی",
    role: "doctor",
    isActive: true,
    doctorId: "doc_1",
    officeId: "off_1",
    lastLoginAt: "2026-10-04T08:30:00.000Z",
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: "2026-10-04T08:30:00.000Z",
  },
  {
    id: "user_doc_2",
    email: "dr.rezaei@medidoc.ir",
    fullName: "دکتر احسان رضایی",
    role: "doctor",
    isActive: true,
    doctorId: "doc_2",
    officeId: "off_2",
    lastLoginAt: "2026-10-03T16:00:00.000Z",
    createdAt: "2026-02-01T11:00:00.000Z",
    updatedAt: "2026-10-03T16:00:00.000Z",
  },
  {
    id: "user_rec_1",
    email: "reception@mehregan.ir",
    fullName: "مریم فراهانی (منشی مطب ونک)",
    role: "receptionist",
    isActive: true,
    officeId: "off_1",
    lastLoginAt: "2026-10-04T08:00:00.000Z",
    createdAt: "2026-02-10T09:00:00.000Z",
    updatedAt: "2026-10-04T08:00:00.000Z",
  },
  {
    id: "user_admin_1",
    email: "admin@medidoc.ir",
    fullName: "مهندس حسینی (مدیر ارشد سامانه)",
    role: "admin",
    isActive: true,
    lastLoginAt: "2026-10-04T07:15:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-10-04T07:15:00.000Z",
  },
];

// ================= DOCTORS =================
export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "doc_1",
    userId: "user_doc_1",
    fullName: "دکتر سارا علوی",
    medicalCouncilNumber: "۱۱۴۵۸۲",
    specialty: "internal",
    clinicName: "مطب تخصصی بیماری‌های داخلی مهرگان (ونک)",
    officeIds: ["off_1", "off_2"],
    city: "تهران",
    bio: "متخصص بیماری‌های داخلی، فارغ‌التحصیل دانشگاه علوم پزشکی تهران با ۱۵ سال سابقه طبابت",
  },
  {
    id: "doc_2",
    userId: "user_doc_2",
    fullName: "دکتر احسان رضایی",
    medicalCouncilNumber: "۹۸۷۴۱",
    specialty: "general",
    clinicName: "درمانگاه شبانه‌روزی سلامت (سعادت‌آباد)",
    officeIds: ["off_2"],
    city: "تهران",
    bio: "پزشک عمومی با گرایش پایش و غربالگری بیماری‌های متابولیک و دیابت",
  },
  {
    id: "doc_3",
    fullName: "دکتر کامران شریفی",
    medicalCouncilNumber: "۸۵۲۱۴",
    specialty: "internal",
    clinicName: "مرکز تخصصی قلب و عروق امید",
    officeIds: ["off_3"],
    city: "تهران",
    bio: "فوق تخصص اکوکاردیوگرافی و پیشگیری از حوادث قلبی عروقی",
  },
  {
    id: "doc_4",
    fullName: "دکتر نیلوفر پارسا",
    medicalCouncilNumber: "۱۲۸۷۹۵",
    specialty: "general",
    clinicName: "کلینیک جامع پزشکی شیراز",
    officeIds: [],
    city: "شیراز",
    bio: "پزشک عمومی و پژوهشگر پرونده الکترونیک سلامت",
  },
];

// ================= PATIENTS =================
export const INITIAL_PATIENTS: Patient[] = [
  {
    id: "pat_1",
    fullName: "محمدجواد کاظمی",
    nationalId: "0068412953",
    phone: "09121112233",
    birthDate: "1351/08/14",
    age: 53,
    sex: "male",
    bloodType: "A+",
    allergies: ["پنی‌سیلین"],
    chronicConditions: ["فشار خون اسنشیال", "کبد چرب گرید ۲"],
    notes: "تحت درمان با لوزارتان ۲۵ و رژیم غذایی کم‌نمک",
    createdByDoctorId: "doc_1",
    createdByOfficeId: "off_1",
    officeName: "مطب تخصصی ونک (مهرگان)",
    createdAt: "2026-08-15T09:30:00.000Z",
    updatedAt: "2026-09-20T11:00:00.000Z",
  },
  {
    id: "pat_2",
    fullName: "مریم فراهانی",
    nationalId: "0440128965",
    phone: "09354445566",
    birthDate: "1369/03/22",
    age: 35,
    sex: "female",
    bloodType: "O+",
    allergies: ["سولفونامیدها"],
    chronicConditions: ["آسم خفیف متناوب"],
    notes: "اسپری سالمترول در فصول سرد مصرف می‌کند",
    createdByDoctorId: "doc_1",
    createdByOfficeId: "off_1",
    officeName: "مطب تخصصی ونک (مهرگان)",
    createdAt: "2026-09-01T14:20:00.000Z",
    updatedAt: "2026-09-28T16:15:00.000Z",
  },
  {
    id: "pat_3",
    fullName: "حاج بهروز افشار",
    nationalId: "0039871120",
    phone: "09123334455",
    birthDate: "1339/10/05",
    age: 65,
    sex: "male",
    bloodType: "B+",
    allergies: [],
    chronicConditions: ["دیابت نوع ۲", "دیس‌لیپیدمی"],
    notes: "مصرف روزانه متفورمین ۱۰۰۰ و آتورواستاتین ۲۰",
    createdByDoctorId: "doc_1",
    createdByOfficeId: "off_2",
    officeName: "درمانگاه شبانه‌روزی سلامت (سعادت‌آباد)",
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-09-25T11:45:00.000Z",
  },
  {
    id: "pat_4",
    fullName: "زهرا صادقی",
    nationalId: "0018529631",
    phone: "09197778899",
    birthDate: "1374/06/11",
    age: 30,
    sex: "female",
    bloodType: "AB+",
    allergies: ["آسپرین"],
    chronicConditions: ["سندرم رفلاکس معده (GERD)"],
    notes: "سابقه سوزش اپی‌گاستر پس از قهوه و ترشیجات",
    createdByDoctorId: "doc_1",
    createdByOfficeId: "off_1",
    officeName: "مطب تخصصی ونک (مهرگان)",
    createdAt: "2026-09-12T11:10:00.000Z",
    updatedAt: "2026-09-29T10:00:00.000Z",
  },
  {
    id: "pat_5",
    fullName: "آرش رضوانی",
    nationalId: "0071425896",
    phone: "09362223344",
    birthDate: "1361/12/03",
    age: 43,
    sex: "male",
    bloodType: "O-",
    allergies: [],
    chronicConditions: ["کمردرد مکانیکال مزمن"],
    notes: "شغل پشت‌میزنشین، توصیه به ورزش روزانه و فیزیوتراپی",
    createdByDoctorId: "doc_2",
    createdByOfficeId: "off_2",
    officeName: "درمانگاه شبانه‌روزی سلامت (سعادت‌آباد)",
    createdAt: "2026-09-18T16:45:00.000Z",
    updatedAt: "2026-09-27T09:20:00.000Z",
  },
  {
    id: "pat_6",
    fullName: "نسرین کریمی",
    nationalId: "0052369874",
    phone: "09126667788",
    birthDate: "1356/04/18",
    age: 49,
    sex: "female",
    bloodType: "A-",
    allergies: ["کدئین"],
    chronicConditions: ["کم‌کاری تیروئید (هاشیموتو)"],
    notes: "لووتیروکسین ۱۰۰ میکروگرم صبح ناشتا",
    createdByDoctorId: "doc_1",
    createdByOfficeId: "off_1",
    officeName: "مطب تخصصی ونک (مهرگان)",
    createdAt: "2026-09-22T08:15:00.000Z",
    updatedAt: "2026-10-01T15:30:00.000Z",
  },
];

// ================= VISITS =================
export const INITIAL_VISITS: Visit[] = [
  {
    id: "vis_1",
    patientId: "pat_1",
    doctorId: "doc_1",
    doctorName: "دکتر سارا علوی",
    officeId: "off_1",
    officeName: "مطب تخصصی ونک (مهرگان)",
    specialty: "internal",
    visitDate: "2026-09-20",
    status: "finalized",
    durationSeconds: 24,
    chiefComplaintIds: ["cc_htn_check", "cc_fatigue"],
    customChiefComplaints: ["سردرد خفیف صبحگاهی از ۳ روز پیش"],
    chiefComplaintsText: ["کنترل دوره‌ای فشار خون", "خستگی مزمن و بی‌حالی"],
    vitals: {
      systolicBp: 145,
      diastolicBp: 92,
      pulse: 78,
      temperature: 36.8,
      weight: 84,
      height: 176,
      bmi: 27.1,
      spo2: 98,
      bloodGlucose: 110,
    },
    examFindingsIds: ["pe_cv_s1s2_nl", "pe_abd_soft", "pe_ext_no_edema"],
    customExamFindings: ["نبض پریفرال قرینه و قوی"],
    examFindingsText: [
      "صدای قلب S1 و S2 نرمال، بدون سوفل",
      "شکم نرم، بدون تندرنس یا ارگانومگالی",
      "اندام‌ها بدون ادم گوده‌گذار یا سیانوز",
    ],
    itemModifiers: {
      pe_cv_s1s2_nl: "ریتم کاملاً منظم، بدون کلیک",
    },
    diagnosisIds: ["dx_essential_htn", "dx_fatty_liver"],
    customDiagnoses: [],
    diagnosesText: [
      "فشار خون اسنشیال اولیه (Essential Hypertension)",
      "کبد چرب غیرالکلی گرید ۲ (NAFLD)",
    ],
    planNotes:
      "۱. لوزارتان از ۲۵ به ۵۰ میلی‌گرم روزانه صبح‌ها افزایش یافت.\n۲. درخواست آزمایش پروفایل چربی (Lipid Profile) و آنزیم‌های کبدی (ALT/AST).\n۳. سونوگرافی کالر داپلر کبد و مجاری صفراوی توصیه شد.\n۴. پیگیری فشار خون ۲ هفته آینده.",
    createdAt: "2026-09-20T10:45:00.000Z",
    updatedAt: "2026-09-20T11:00:00.000Z",
    finalizedAt: "2026-09-20T11:00:00.000Z",
  },
  {
    id: "vis_2",
    patientId: "pat_2",
    doctorId: "doc_1",
    doctorName: "دکتر سارا علوی",
    officeId: "off_1",
    officeName: "مطب تخصصی ونک (مهرگان)",
    specialty: "internal",
    visitDate: "2026-09-28",
    status: "finalized",
    durationSeconds: 22,
    chiefComplaintIds: ["cc_cough_dry", "cc_dyspnea_mild"],
    customChiefComplaints: [],
    chiefComplaintsText: ["سرفه خشک و تحریکی", "تنگی نفس خفیف در فعالیت"],
    vitals: {
      systolicBp: 118,
      diastolicBp: 75,
      pulse: 82,
      temperature: 37.1,
      weight: 62,
      height: 165,
      bmi: 22.8,
      spo2: 97,
      respiratoryRate: 18,
    },
    examFindingsIds: ["pe_pulm_wheeze_exp", "pe_heent_pharynx_nl"],
    customExamFindings: [],
    examFindingsText: [
      "ویزینگ بازدمی منتشر در قاعده هر دو ریه",
      "حلق و لوزه‌ها بدون اگزودا یا اریتم شدید",
    ],
    diagnosisIds: ["dx_asthma_acute", "dx_allergic_rhinitis"],
    customDiagnoses: [],
    diagnosesText: [
      "حمله خفیف آسم برونشیال (Mild Bronchial Asthma Exacerbation)",
      "رینیت آلرژیک فصلی (Allergic Rhinitis)",
    ],
    planNotes:
      "۱. اسپری سالمترول/فلوتیکازون (سرتاید ۲۵۰) روزی ۲ پاف هر ۱۲ ساعت.\n۲. اسپری سالبوتامول موقع تنگی نفس حاد.\n۳. پرهیز از محرک‌ها، دود سیگار و هوای آلوده.\n۴. اسپیرومتری پس از بهبود علائم حاد.",
    createdAt: "2026-09-28T16:00:00.000Z",
    updatedAt: "2026-09-28T16:15:00.000Z",
    finalizedAt: "2026-09-28T16:15:00.000Z",
  },
  {
    id: "vis_3",
    patientId: "pat_3",
    doctorId: "doc_1",
    doctorName: "دکتر سارا علوی",
    officeId: "off_2",
    officeName: "درمانگاه شبانه‌روزی سلامت (سعادت‌آباد)",
    specialty: "internal",
    visitDate: "2026-09-25",
    status: "finalized",
    durationSeconds: 28,
    chiefComplaintIds: ["cc_routine_check", "cc_polyuria"],
    customChiefComplaints: ["کرختی انگشتان پا در شب"],
    chiefComplaintsText: ["چکاپ روتین و تمدید دارو", "پرادراری و پرنوشی"],
    vitals: {
      systolicBp: 135,
      diastolicBp: 85,
      pulse: 74,
      temperature: 36.6,
      weight: 88,
      height: 172,
      bmi: 29.7,
      bloodGlucose: 168,
      spo2: 96,
    },
    examFindingsIds: ["pe_cv_s1s2_nl", "pe_abd_soft", "pe_neuro_reflex_nl"],
    customExamFindings: ["حس لرزش پاشنه پا اندکی کاهش یافته"],
    examFindingsText: [
      "صدای قلب S1 و S2 نرمال، بدون سوفل",
      "شکم نرم، بدون تندرنس یا ارگانومگالی",
      "رفلکس‌های وتری عمیق (DTR) نرمال و قرینه",
    ],
    diagnosisIds: ["dx_type2_diabetes", "dx_dyslipidemia"],
    customDiagnoses: ["احتمال نوروپاتی محیطی دیابتی اولیه"],
    diagnosesText: [
      "دیابت قندی نوع ۲ کنترل‌نشده (Type 2 Diabetes)",
      "دیس‌لیپیدمی و هیپرکلسترولمی (Hyperlipidemia)",
    ],
    planNotes:
      "۱. آزمایش HbA1c، کراتینین، اوره، میکروآلبومینوری ادرار ۲۴ ساعته.\n۲. دوز متفورمین به ۱۰۰۰ میلی‌گرم ۲ بار در روز با غذا افزایش یافت.\n۳. ارجاع جهت معاینه فوندوسکوپی سالانه به چشم‌پزشک.\n۴. آموزش مراقبت از پای دیابتی.",
    createdAt: "2026-09-25T11:20:00.000Z",
    updatedAt: "2026-09-25T11:45:00.000Z",
    finalizedAt: "2026-09-25T11:45:00.000Z",
  },
  {
    id: "vis_4",
    patientId: "pat_4",
    doctorId: "doc_1",
    doctorName: "دکتر سارا علوی",
    officeId: "off_1",
    officeName: "مطب تخصصی ونک (مهرگان)",
    specialty: "internal",
    visitDate: "2026-09-29",
    status: "finalized",
    durationSeconds: 20,
    chiefComplaintIds: ["cc_epigastric_pain", "cc_heartburn"],
    customChiefComplaints: [],
    chiefComplaintsText: ["درد و سوزش سر دل", "سوزش پشت جناغ (Heartburn)"],
    vitals: {
      systolicBp: 110,
      diastolicBp: 70,
      pulse: 76,
      temperature: 36.9,
      weight: 56,
      height: 160,
      bmi: 21.9,
      spo2: 99,
    },
    examFindingsIds: ["pe_abd_tender_epigastric"],
    customExamFindings: [],
    examFindingsText: ["تندرنس خفیف در لمس اپی‌گاستر بدون ریباند یا گاردینگ"],
    itemModifiers: {
      pe_abd_tender_epigastric: "در لمس ملایم، بدون نشانه‌ای از پریتونیت",
    },
    diagnosisIds: ["dx_gerd", "dx_gastritis_acute"],
    customDiagnoses: [],
    diagnosesText: [
      "بیماری ریفلاکس معده به مری (GERD)",
      "گاستریت حاد و سوء هاضمه عملکردی (Dyspepsia)",
    ],
    planNotes:
      "۱. کپسول امپرازول ۲۰ میلی‌گرم صبح‌ها نیم ساعت قبل از صبحانه.\n۲. شربت آلومینیوم ام‌جی‌اس بعد از غذا در صورت سوزش شدید.\n۳. پرهیز از خوابیدن تا ۲ ساعت پس از غذا، کاهش مصرف کافئین، ادویه و مرکبات.",
    createdAt: "2026-09-29T09:40:00.000Z",
    updatedAt: "2026-09-29T10:00:00.000Z",
    finalizedAt: "2026-09-29T10:00:00.000Z",
  },
];

// ================= SUBSCRIPTION PLANS (Doc 08) =================
export const MOCK_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: "plan_trial",
    name: "trial",
    displayName: "آزمایشی رایگان (Trial)",
    maxPatients: 20,
    priceMonthly: 0,
    priceAnnual: 0,
    maxOffices: 1,
    maxReceptionists: 0,
    maxConnections: 0,
    hasAiVoice: false,
    features: [
      "سقف ۲۰ پرونده بیمار",
      "۱۴ روز دسترسی آزمایشی",
      "ثبت فوق‌سریع ویزیت ساختاریافته",
      "۱ مطب فعال",
      "پشتیبان‌گیری دستی JSON",
      "واترمارک MediDoc در پرینت",
    ],
    isActive: true,
  },
  {
    id: "plan_bronze",
    name: "bronze",
    displayName: "طرح برنزی (Bronze)",
    maxPatients: 100,
    priceMonthly: 450000,
    priceAnnual: 4500000,
    maxOffices: 1,
    maxReceptionists: 1,
    maxConnections: 5,
    hasAiVoice: false,
    features: [
      "سقف ۱۰۰ پرونده بیمار",
      "۱ مطب فعال",
      "۱ منشی مطب با دسترسی مجزا",
      "اتصال به حداکثر ۵ همکار پزشک",
      "اشتراک‌گذاری محدود بیماران",
      "خروجی چاپی بدون واترمارک",
      "پشتیبانی تیکتی و ایمیل",
    ],
    isActive: true,
  },
  {
    id: "plan_silver",
    name: "silver",
    displayName: "طرح نقره‌ای (Silver)",
    maxPatients: 500,
    priceMonthly: 950000,
    priceAnnual: 9500000,
    maxOffices: 3,
    maxReceptionists: 3,
    maxConnections: 20,
    hasAiVoice: false,
    features: [
      "سقف ۵۰۰ پرونده بیمار",
      "۳ مطب مستقل با سوییچ آسان",
      "۳ منشی با تفکیک مطب",
      "شبکه ارتباط با ۲۰ پزشک همکار",
      "اشتراک‌گذاری کامل بیمار با رضایت",
      "داشبورد آمار و تحلیل راندمان مطب",
      "پشتیبان‌گیری خودکار روزانه",
      "پشتیبانی آنلاین و چت مستقیم",
    ],
    isActive: true,
  },
  {
    id: "plan_gold",
    name: "gold",
    displayName: "طرح طلایی هوشمند (Gold + AI)",
    maxPatients: -1, // Unlimited
    priceMonthly: 1850000,
    priceAnnual: 18500000,
    maxOffices: 999,
    maxReceptionists: 999,
    maxConnections: 999,
    hasAiVoice: true,
    features: [
      "پرونده بیمار نامحدود",
      "مطب‌ها و درمانگاه‌های نامحدود",
      "دیکته صوتی هوش مصنوعی (AI Voice 🎤)",
      "استخراج خودکار علائم، معاینه و تشخیص",
      "مدیریت خطای نگاشت (Escape Hatches)",
      "تعداد نامحدود منشی و همکار متصل",
      "پشتیبان‌گیری لحظه‌ای و ابری",
      "پشتیبانی VIP و خط تلفن اختصاصی",
    ],
    isActive: true,
  },
];

// Active Subscription for Dr. Alavi
export const INITIAL_DOCTOR_SUBSCRIPTION: DoctorSubscription = {
  id: "sub_doc_1",
  doctorId: "doc_1",
  planId: "plan_silver",
  planName: "silver",
  status: "active",
  currentPeriodStart: "2026-09-15T00:00:00.000Z",
  currentPeriodEnd: "2026-10-15T23:59:59.000Z",
  trialEndsAt: null,
  autoRenew: true,
  createdAt: "2026-06-15T12:00:00.000Z",
  updatedAt: "2026-09-15T00:00:00.000Z",
};

// Payment transactions
export const INITIAL_PAYMENT_TRANSACTIONS: PaymentTransaction[] = [
  {
    id: "tx_1",
    doctorId: "doc_1",
    subscriptionId: "sub_doc_1",
    planName: "طرح نقره‌ای — تمدید شهریور ۱۴۰۵",
    amount: 950000,
    currency: "تومان",
    gateway: "زرین‌پال (ZarinPal)",
    gatewayRefId: "ZAR-9812401",
    status: "success",
    paidAt: "2026-09-15T09:14:20.000Z",
    createdAt: "2026-09-15T09:12:00.000Z",
  },
  {
    id: "tx_2",
    doctorId: "doc_1",
    subscriptionId: "sub_doc_1",
    planName: "طرح نقره‌ای — تمدید مرداد ۱۴۰۵",
    amount: 950000,
    currency: "تومان",
    gateway: "زرین‌پال (ZarinPal)",
    gatewayRefId: "ZAR-7741290",
    status: "success",
    paidAt: "2026-08-15T10:05:12.000Z",
    createdAt: "2026-08-15T10:02:00.000Z",
  },
  {
    id: "tx_3",
    doctorId: "doc_1",
    subscriptionId: "sub_doc_1",
    planName: "طرح نقره‌ای — تمدید تیر ۱۴۰۵",
    amount: 950000,
    currency: "تومان",
    gateway: "آیدی‌پی (IDPay)",
    gatewayRefId: "IDP-440182",
    status: "success",
    paidAt: "2026-07-15T11:20:45.000Z",
    createdAt: "2026-07-15T11:18:00.000Z",
  },
];

// Doctor Connections (Doc 07)
export const INITIAL_DOCTOR_CONNECTIONS: DoctorConnection[] = [
  {
    id: "conn_1",
    requesterId: "doc_1",
    receiverId: "doc_2",
    status: "accepted",
    requestedAt: "2026-07-01T10:00:00.000Z",
    respondedAt: "2026-07-01T14:30:00.000Z",
  },
  {
    id: "conn_2",
    requesterId: "doc_3",
    receiverId: "doc_1",
    status: "pending", // Incoming request for Dr. Alavi
    requestedAt: "2026-10-02T16:00:00.000Z",
    respondedAt: null,
  },
  {
    id: "conn_3",
    requesterId: "doc_1",
    receiverId: "doc_4",
    status: "pending", // Sent by Dr. Alavi to Dr. Parsa
    requestedAt: "2026-09-28T09:00:00.000Z",
    respondedAt: null,
  },
];

// Shared Patients (Doc 07)
export const INITIAL_SHARED_PATIENTS: SharedPatient[] = [
  {
    id: "shp_1",
    patientId: "pat_1",
    ownerDoctorId: "doc_1",
    ownerDoctorName: "دکتر سارا علوی",
    sharedWithDoctorId: "doc_2",
    sharedWithDoctorName: "دکتر احسان رضایی",
    accessLevel: "read_write",
    patientConsent: true,
    notes: "جهت مشاوره غربالگری فشار خون مقاوم و پایش دیابت در درمانگاه سلامت",
    sharedAt: "2026-09-22T10:00:00.000Z",
    revokedAt: null,
    isActive: true,
  },
];

// Audit Trail Logs (Doc 05 & 06)
export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud_1",
    userId: "user_doc_1",
    userName: "دکتر سارا علوی",
    userRole: "doctor",
    action: "patient.share",
    entityType: "SharedPatient",
    entityId: "pat_1",
    metadata: {
      sharedWith: "دکتر احسان رضایی",
      accessLevel: "read_write",
      consentChecked: true,
    },
    ipAddress: "5.127.88.14",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128",
    createdAt: "2026-09-22T10:00:00.000Z",
  },
  {
    id: "aud_2",
    userId: "user_doc_1",
    userName: "دکتر سارا علوی",
    userRole: "doctor",
    action: "visit.finalize",
    entityType: "Visit",
    entityId: "vis_1",
    metadata: {
      patientId: "pat_1",
      durationSeconds: 24,
      diagnosis: "Essential Hypertension",
    },
    ipAddress: "5.127.88.14",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128",
    createdAt: "2026-09-20T11:00:00.000Z",
  },
  {
    id: "aud_3",
    userId: "user_rec_1",
    userName: "مریم فراهانی (منشی)",
    userRole: "receptionist",
    action: "patient.create",
    entityType: "Patient",
    entityId: "pat_6",
    metadata: {
      fullName: "نسرین کریمی",
      phone: "09126667788",
      officeId: "off_1",
    },
    ipAddress: "5.127.88.14",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128",
    createdAt: "2026-09-22T08:15:00.000Z",
  },
  {
    id: "aud_4",
    userId: "user_admin_1",
    userName: "مهندس حسینی (ادمین)",
    userRole: "admin",
    action: "user.role_assigned",
    entityType: "User",
    entityId: "user_rec_1",
    metadata: {
      role: "receptionist",
      office: "مطب تخصصی ونک (مهرگان)",
    },
    ipAddress: "185.143.232.10",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    createdAt: "2026-02-10T09:00:00.000Z",
  },
];
