import { SpecialtyTemplatePhrase } from "@/types/medical";

export const INITIAL_TEMPLATES: SpecialtyTemplatePhrase[] = [
  // ================= GENERAL MEDICINE - CHIEF COMPLAINTS =================
  {
    id: "gen_cc_1",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "تب و لرز خفیف تا متوسط",
    code: "R50.9",
    order: 1,
  },
  {
    id: "gen_cc_2",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "گلودرد حاد و سوزش گلو",
    code: "J02.9",
    order: 2,
  },
  {
    id: "gen_cc_3",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "سرفه خشک و تحریکی",
    code: "R05.1",
    order: 3,
  },
  {
    id: "gen_cc_4",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "سرفه خلط‌دار (خلط سفید یا زرد)",
    code: "R05.2",
    order: 4,
  },
  {
    id: "gen_cc_5",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "آبریزش بینی و احتقان سینوسی",
    code: "R09.81",
    order: 5,
  },
  {
    id: "gen_cc_6",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "سردرد فشاری/تنشی دوطرفه",
    code: "G44.2",
    order: 6,
  },
  {
    id: "gen_cc_7",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "سوزش ادرار و تکرر ادرار",
    code: "R30.0",
    order: 7,
  },
  {
    id: "gen_cc_8",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "درد شکم کرامپی همراه با تهوع",
    code: "R10.4",
    order: 8,
  },
  {
    id: "gen_cc_9",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "اسهال حاد آبکی بدون خون",
    code: "A09",
    order: 9,
  },
  {
    id: "gen_cc_10",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "ضعف عمومی، بدن‌درد و بی‌حالی",
    code: "R53.83",
    order: 10,
  },
  {
    id: "gen_cc_11",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "سرگیجه خفیف چرخشی/وضعیتی",
    code: "R42",
    order: 11,
  },
  {
    id: "gen_cc_12",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "کمردرد حاد مکانیکال پس از فعالیت",
    code: "M54.5",
    order: 12,
  },
  {
    id: "gen_cc_13",
    specialty: "general",
    section: "chief_complaint",
    phraseText: "مراجعه جهت چکاپ روتین و تمدید دارو",
    code: "Z00.00",
    order: 13,
  },

  // ================= INTERNAL MEDICINE - CHIEF COMPLAINTS =================
  {
    id: "int_cc_1",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "تنگی نفس فعالیتی (DOE Grade II/III)",
    code: "R06.02",
    order: 1,
  },
  {
    id: "int_cc_2",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "کنترل فشار خون و نوسانات فشار",
    code: "I10",
    order: 2,
  },
  {
    id: "int_cc_3",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "کنترل قند خون / علائم تشنگی و پرادراری",
    code: "E11.9",
    order: 3,
  },
  {
    id: "int_cc_4",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "سوزش سر دل و ترش کردن مزمن (GERD)",
    code: "K21.9",
    order: 4,
  },
  {
    id: "int_cc_5",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "درد مبهم اپی‌گاستر پس از صرف غذا",
    code: "R10.13",
    order: 5,
  },
  {
    id: "int_cc_6",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "تپش قلب متناوب بدون سینکوپ",
    code: "R00.2",
    order: 6,
  },
  {
    id: "int_cc_7",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "ادم و تورم دوطرفه اندام تحتانی",
    code: "R60.0",
    order: 7,
  },
  {
    id: "int_cc_8",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "خستگی مزمن، ضعف و رنگ‌پریدگی (بررسی کم‌خونی)",
    code: "D50.9",
    order: 8,
  },
  {
    id: "int_cc_9",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "کاهش یا افزایش وزن غیرمنتظره در ماه‌های اخیر",
    code: "R63.4",
    order: 9,
  },
  {
    id: "int_cc_10",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "اختلال دفع گوارشی (یبوست مزمن / متناوب با اسهال)",
    code: "K59.00",
    order: 10,
  },
  {
    id: "int_cc_11",
    specialty: "internal",
    section: "chief_complaint",
    phraseText: "پیگیری سونوگرافی کبد چرب و آنزیم‌های کبدی",
    code: "K76.0",
    order: 11,
  },

  // ================= PHYSICAL EXAM FINDINGS (SHARED / ORGAN SYSTEMS) =================
  // System: عمومی (General)
  {
    id: "pe_gen_1",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "عمومی",
    phraseText: "بیمار هوشیار، جهت‌یاب و دارای ظاهر بالینی پایدار (Alert & Stable)",
    order: 1,
  },
  {
    id: "pe_gen_2",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "عمومی",
    phraseText: "تب‌دار با تعریق خفیف، مخاطات کمی خشک",
    order: 2,
  },
  {
    id: "pe_gen_3",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "عمومی",
    phraseText: "رنگ‌پریدگی در ملتحمه و بستر ناخن مشهود است",
    order: 3,
  },

  // System: سر و گردن (HEENT)
  {
    id: "pe_heent_1",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "سر و گردن (HEENT)",
    phraseText: "فارنکس احتقانی با اریتم، بدون اگزودای چرکی لوزه‌ها",
    order: 4,
  },
  {
    id: "pe_heent_2",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "سر و گردن (HEENT)",
    phraseText: "حلق و لوزه‌ها کاملاً نرمال، بدون اریتم و اگزودا",
    order: 5,
  },
  {
    id: "pe_heent_3",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "سر و گردن (HEENT)",
    phraseText: "حساسیت موضعی در لمس سینوس‌های ماگزیلاری و فرونتال",
    order: 6,
  },
  {
    id: "pe_heent_4",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "سر و گردن (HEENT)",
    phraseText: "غدد لنفاوی گردنی قدامی بزرگ و تندر (LAD+)",
    order: 7,
  },
  {
    id: "pe_heent_5",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "سر و گردن (HEENT)",
    phraseText: "غده تیروئید بدون بزرگی منتشر یا ندول لمس‌پذیر",
    order: 8,
  },

  // System: تنفسی (Respiratory / Chest)
  {
    id: "pe_resp_1",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "تنفسی (ریه)",
    phraseText: "صداهای تنفسی دوطرفه شفاف و قرینه، بدون رال یا ویزینگ (Clear BS)",
    order: 9,
  },
  {
    id: "pe_resp_2",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "تنفسی (ریه)",
    phraseText: "ویزینگ بازدمی منتشر در هر دو فیلد ریوی",
    order: 10,
  },
  {
    id: "pe_resp_3",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "تنفسی (ریه)",
    phraseText: "رال کرپیتاسیون ظریف در قاعده‌ی هر دو ریه (Bilateral Basal Crackles)",
    order: 11,
  },
  {
    id: "pe_resp_4",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "تنفسی (ریه)",
    phraseText: "رونکای خشن در لوب میانی راست/چپ",
    order: 12,
  },

  // System: قلبی-عروقی (Cardiovascular)
  {
    id: "pe_cv_1",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "قلبی-عروقی",
    phraseText: "صداهای قلبی S1 و S2 نرمال، بدون سوفل، ریتم منظم",
    order: 13,
  },
  {
    id: "pe_cv_2",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "قلبی-عروقی",
    phraseText: "سوفل سیستولیک درجه 2/6 در کانون آئورت/مایترال",
    order: 14,
  },
  {
    id: "pe_cv_3",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "قلبی-عروقی",
    phraseText: "نبض‌های محیطی رادیال و پدال پر و قرینه",
    order: 15,
  },
  {
    id: "pe_cv_4",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "قلبی-عروقی",
    phraseText: "ادم گوده‌گذار اندام تحتانی درجه ۱+ تا ۲+ (Pitting Edema)",
    order: 16,
  },
  {
    id: "pe_cv_5",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "قلبی-عروقی",
    phraseText: "بدون اتساع ورید ژوگولار (JVD منفی)",
    order: 17,
  },

  // System: شکم و گوارش (Abdomen)
  {
    id: "pe_abd_1",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "شکم و دستگاه گوارش",
    phraseText: "شکم نرم و غیرحساس در لمس سطحی و عمقی، بدون گاردینگ",
    order: 18,
  },
  {
    id: "pe_abd_2",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "شکم و دستگاه گوارش",
    phraseText: "تندرنس خفیف در ناحیه اپی‌گاستر بدون ریباند",
    order: 19,
  },
  {
    id: "pe_abd_3",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "شکم و دستگاه گوارش",
    phraseText: "صداهای روده‌ای نرمال و فعال (Normal Bowel Sounds)",
    order: 20,
  },
  {
    id: "pe_abd_4",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "شکم و دستگاه گوارش",
    phraseText: "کبد و طحال در زیر لبه دنده‌ای لمس نمی‌شوند (No HSM)",
    order: 21,
  },
  {
    id: "pe_abd_5",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "شکم و دستگاه گوارش",
    phraseText: "علامت مورفی و مک‌بورنی هر دو منفی",
    order: 22,
  },

  // System: عضلانی-اسکلتی (Musculoskeletal)
  {
    id: "pe_msk_1",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "عضلانی-اسکلتی",
    phraseText: "اسپاسم و تندرنس موضعی در عضلات پاراورتبرال کمری",
    order: 23,
  },
  {
    id: "pe_msk_2",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "عضلانی-اسکلتی",
    phraseText: "تست Straight Leg Raise (SLR) در هر دو سمت تا ۸۰ درجه منفی",
    order: 24,
  },
  {
    id: "pe_msk_3",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "عضلانی-اسکلتی",
    phraseText: "مفاصل محیطی بدون تورم، قرمزی، گرما یا محدودیت حرکتی",
    order: 25,
  },

  // System: مغز و اعصاب (Neurology)
  {
    id: "pe_neuro_1",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "مغز و اعصاب",
    phraseText: "مردمک‌ها ایزوکوریک و واکنش به نور طبیعی (PERRLA)",
    order: 26,
  },
  {
    id: "pe_neuro_2",
    specialty: "general",
    section: "exam_finding",
    systemGroup: "مغز و اعصاب",
    phraseText: "علامت سفتی گردن و کرنیگ منفی (No meningeal signs)",
    order: 27,
  },
  {
    id: "pe_neuro_3",
    specialty: "internal",
    section: "exam_finding",
    systemGroup: "مغز و اعصاب",
    phraseText: "حس محیطی در دست‌ها و پاها حفظ شده (نوروپاتی خفیف دیابتی منفی)",
    order: 28,
  },

  // ================= DIAGNOSES (GENERAL MEDICINE) =================
  {
    id: "gen_dx_1",
    specialty: "general",
    section: "diagnosis",
    phraseText: "عفونت حاد مجاری تنفسی فوقانی ویروسی (Viral URI)",
    code: "J06.9",
    order: 1,
  },
  {
    id: "gen_dx_2",
    specialty: "general",
    section: "diagnosis",
    phraseText: "فارنژیت حاد غیراستروپتوکوکی",
    code: "J02.9",
    order: 2,
  },
  {
    id: "gen_dx_3",
    specialty: "general",
    section: "diagnosis",
    phraseText: "گاستروانتریت حاد ویروسی / مسمومیت خفیف غذایی",
    code: "A08.4",
    order: 3,
  },
  {
    id: "gen_dx_4",
    specialty: "general",
    section: "diagnosis",
    phraseText: "عفونت بدون عارضه دستگاه ادراری تحتانی (Cystitis)",
    code: "N30.0",
    order: 4,
  },
  {
    id: "gen_dx_5",
    specialty: "general",
    section: "diagnosis",
    phraseText: "سردرد تنشی اولیه (Tension-Type Headache)",
    code: "G44.209",
    order: 5,
  },
  {
    id: "gen_dx_6",
    specialty: "general",
    section: "diagnosis",
    phraseText: "اسپاسم حاد عضلانی لومبار (Acute Lumbar Strain)",
    code: "S39.012A",
    order: 6,
  },
  {
    id: "gen_dx_7",
    specialty: "general",
    section: "diagnosis",
    phraseText: "رینوسینوزیت حاد با منشا ویروسی",
    code: "J01.90",
    order: 7,
  },
  {
    id: "gen_dx_8",
    specialty: "general",
    section: "diagnosis",
    phraseText: "ارزیابی سلامت و چکاپ دوره‌ای بدون یافته غیرطبیعی",
    code: "Z00.00",
    order: 8,
  },

  // ================= DIAGNOSES (INTERNAL MEDICINE) =================
  {
    id: "int_dx_1",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "فشار خون اولیه اسنشیال (Essential Hypertension)",
    code: "I10",
    order: 1,
  },
  {
    id: "int_dx_2",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "دیابت ملیتوس نوع ۲ با کنترل متوسط (Type 2 Diabetes Mellitus)",
    code: "E11.69",
    order: 2,
  },
  {
    id: "int_dx_3",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "بیماری رفلاکس معده به مری (GERD) با ازوفاژیت خفیف",
    code: "K21.0",
    order: 3,
  },
  {
    id: "int_dx_4",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "دیس‌لیپیدمی مخلوط / هایپرکلسترولمی",
    code: "E78.2",
    order: 4,
  },
  {
    id: "int_dx_5",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "کبد چرب غیرالکلی گرید ۱ تا ۲ (NAFLD)",
    code: "K76.0",
    order: 5,
  },
  {
    id: "int_dx_6",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "کم‌خونی فقر آهن متوسط (Iron Deficiency Anemia)",
    code: "D50.9",
    order: 6,
  },
  {
    id: "int_dx_7",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "کم‌کاری تیروئید اولیه تحت درمان (Hypothyroidism)",
    code: "E03.9",
    order: 7,
  },
  {
    id: "int_dx_8",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "سندرم روده تحریک‌پذیر نوع غالب یبوست (IBS-C)",
    code: "K58.1",
    order: 8,
  },
  {
    id: "int_dx_9",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "هیپراوریسمی بدون نقرس مفصلی حاد",
    code: "E79.0",
    order: 9,
  },
  {
    id: "int_dx_10",
    specialty: "internal",
    section: "diagnosis",
    phraseText: "برونشیت مزمن همراه با علائم انسدادی خفیف",
    code: "J42",
    order: 10,
  },
];
